
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <section className="section bg-interpretis-darker" id="disclaimer">
      <div className="container-custom">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            <span className="text-gradient">Legal Disclaimer</span>
          </h2>
        </div>
        
        <div className="glassmorphic-card p-6 md:p-8 max-w-4xl mx-auto">
          <div className="space-y-6 text-interpretis-muted">
            <p>
              <strong>Disclaimer of Liability:</strong> Interpretis 🕰️ AI is provided "as is" and "as available" without warranties of any kind, either expressed or implied. AI WEB TOOLS LLC does not warrant that the service will be uninterrupted or error-free.
            </p>
            
            <p>
              <strong>Accuracy of Information:</strong> While we strive to provide accurate and insightful analyses, Interpretis 🕰️ AI is an AI-powered tool that synthesizes information from various sources. The etymological, historical, and cultural analyses provided should not be considered definitive or authoritative. Users should verify important information through additional academic or professional sources.
            </p>
            
            <p>
              <strong>Educational Purpose:</strong> Interpretis 🕰️ AI is designed for educational and entertainment purposes only. It should not be used as a sole source for academic research, professional, legal, medical, or financial decisions.
            </p>
            
            <p>
              <strong>Content Responsibility:</strong> AI WEB TOOLS LLC is not responsible for any actions taken by users based on the information provided by Interpretis 🕰️ AI. Users accept full responsibility for their use of the information provided.
            </p>
            
            <p>
              <strong>Third-Party Links:</strong> Interpretis 🕰️ AI may provide links to third-party websites or resources. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services.
            </p>
            
            <p>
              <strong>Intellectual Property:</strong> The analyses generated by Interpretis 🕰️ AI are based on existing knowledge and do not create new intellectual property rights. Users should respect copyright and intellectual property laws when using the information provided.
            </p>
            
            <p>
              <strong>Service Changes:</strong> AI WEB TOOLS LLC reserves the right to modify or discontinue, temporarily or permanently, the service without notice. We shall not be liable for any modification, suspension, or discontinuance of the service.
            </p>
            
            <p>
              <strong>Usage Through ChatGPT:</strong> Interpretis 🕰️ AI is accessed through ChatGPT and is subject to OpenAI's terms of service and privacy policy. Users must comply with all applicable OpenAI policies when using Interpretis.
            </p>
            
            <p>
              <strong>Governing Law:</strong> This disclaimer and your use of Interpretis 🕰️ AI shall be governed by and construed in accordance with the laws of the jurisdiction in which AI WEB TOOLS LLC operates, without regard to its conflict of law provisions.
            </p>
            
            <p>
              By using Interpretis 🕰️ AI, you acknowledge that you have read, understood, and agree to be bound by this disclaimer.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
